CREATE TABLE "ERROR_TYPES" (
    "ERROR_TYPE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START
    WITH
        1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL ENABLE,
        "ERROR_NAME" VARCHAR2 (50 CHAR) NOT NULL ENABLE,
        CONSTRAINT "ERROR_TYPES_PK" PRIMARY KEY ("ERROR_TYPE_ID") USING INDEX ENABLE,
        CONSTRAINT "ERROR_TYPES_UK" UNIQUE ("ERROR_NAME") USING INDEX ENABLE
);