CREATE TABLE "FEEDBACK" (
    "FEEDBACK_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START
    WITH
        1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL ENABLE,
        "ERROR_ID" NUMBER NOT NULL ENABLE,
        "USERNAME" VARCHAR2 (50 CHAR) NOT NULL ENABLE,
        "FEEDBACK_TEXT" VARCHAR2 (4000 CHAR) NOT NULL ENABLE,
        "FEEDBACK_DATE" TIMESTAMP(6) DEFAULT systimestamp NOT NULL ENABLE,
        CONSTRAINT "FEEDBACK_PK" PRIMARY KEY ("FEEDBACK_ID") USING INDEX ENABLE,
        CONSTRAINT "FEEDBACK_ERROR_UK" UNIQUE ("ERROR_ID") USING INDEX ENABLE
);

ALTER TABLE "FEEDBACK"
ADD CONSTRAINT "FEEDBACK_ERROR_FK" FOREIGN KEY ("ERROR_ID") REFERENCES "RESPONSE_ERRORS" ("ERROR_ID") ENABLE;

ALTER TABLE "FEEDBACK"
ADD CONSTRAINT "FEEDBACK_USER_FK" FOREIGN KEY ("USERNAME") REFERENCES "APP_USERS" ("USERNAME") ENABLE;