CREATE TABLE "RESPONSES" (
    "RESPONSE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START
    WITH
        1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL ENABLE,
        "USERNAME" VARCHAR2 (50 CHAR) NOT NULL ENABLE,
        "SYSTEM_ID" NUMBER NOT NULL ENABLE,
        "PURPOSE_TEXT" VARCHAR2 (4000 CHAR),
        "COMPONENTS_TEXT" VARCHAR2 (4000 CHAR),
        "INTERACTIONS_TEXT" VARCHAR2 (4000 CHAR),
        "VARIABLES_TEXT" VARCHAR2 (4000 CHAR),
        "CONSTANTS_TEXT" VARCHAR2 (4000 CHAR),
        "CREATED_AT" TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
        "API_RESPONSE_JSON" CLOB,
        CONSTRAINT "RESPONSES_PK" PRIMARY KEY ("RESPONSE_ID") USING INDEX ENABLE
);

ALTER TABLE "RESPONSES"
ADD CONSTRAINT "RESPONSES_USER_FK" FOREIGN KEY ("USERNAME") REFERENCES "APP_USERS" ("USERNAME") ENABLE;

ALTER TABLE "RESPONSES"
ADD CONSTRAINT "RESPONSES_SYSTEM_FK" FOREIGN KEY ("SYSTEM_ID") REFERENCES "SYSTEMS" ("SYSTEM_ID") ENABLE;