CREATE TABLE "RESPONSE_ERRORS" (
    "ERROR_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START
    WITH
        1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL ENABLE,
        "RESPONSE_ID" NUMBER NOT NULL ENABLE,
        "CATEGORY_ID" NUMBER NOT NULL ENABLE,
        "ERROR_TYPE_ID" NUMBER NOT NULL ENABLE,
        "STUDENT_VALUE" VARCHAR2 (4000 CHAR) NOT NULL ENABLE,
        "SUBERROR_CODE" VARCHAR2 (150),
        CONSTRAINT "RESPONSE_ERRORS_PK" PRIMARY KEY ("ERROR_ID") USING INDEX ENABLE
);

ALTER TABLE "RESPONSE_ERRORS"
ADD CONSTRAINT "RESPONSE_ERRORS_RESPONSE_FK" FOREIGN KEY ("RESPONSE_ID") REFERENCES "RESPONSES" ("RESPONSE_ID") ENABLE;

ALTER TABLE "RESPONSE_ERRORS"
ADD CONSTRAINT "RESPONSE_ERRORS_CATEGORY_FK" FOREIGN KEY ("CATEGORY_ID") REFERENCES "RESPONSE_CATEGORIES" ("CATEGORY_ID") ENABLE;

ALTER TABLE "RESPONSE_ERRORS"
ADD CONSTRAINT "RESPONSE_ERRORS_TYPE_FK" FOREIGN KEY ("ERROR_TYPE_ID") REFERENCES "ERROR_TYPES" ("ERROR_TYPE_ID") ENABLE;

CREATE INDEX "RESPONSE_ERRORS_I1" ON "RESPONSE_ERRORS" ("RESPONSE_ID");