CREATE TABLE "RESPONSE_CATEGORIES" (
    "CATEGORY_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START
    WITH
        1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL ENABLE,
        "CATEGORY_NAME" VARCHAR2 (30 CHAR) NOT NULL ENABLE,
        CONSTRAINT "RESPONSE_CATEGORIES_PK" PRIMARY KEY ("CATEGORY_ID") USING INDEX ENABLE,
        CONSTRAINT "RESPONSE_CATEGORIES_UK" UNIQUE ("CATEGORY_NAME") USING INDEX ENABLE
);