CREATE TABLE "SYSTEMS" (
    "SYSTEM_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START
    WITH
        1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL ENABLE,
        "ASSIGNMENT_ID" NUMBER NOT NULL ENABLE,
        "SYSTEM_NAME" VARCHAR2 (100 CHAR) NOT NULL ENABLE,
        "SYSTEM_CODE" VARCHAR2 (30),
        CONSTRAINT "SYSTEMS_PK" PRIMARY KEY ("SYSTEM_ID") USING INDEX ENABLE,
        CONSTRAINT "SYSTEMS_CODE_UK" UNIQUE ("SYSTEM_CODE") USING INDEX ENABLE
);

ALTER TABLE "SYSTEMS"
ADD CONSTRAINT "SYSTEMS_ASSIGNMENT_FK" FOREIGN KEY ("ASSIGNMENT_ID") REFERENCES "ASSIGNMENTS" ("ASSIGNMENT_ID") ENABLE;